set MATLAB=C:\MATLAB\R2019a
C:\MATLAB\R2019a\bin\win64\gmake -f aurix_mbd_test.mk  GENERATE_ASAP2=0 HITEX_AURIX_AUTOMATIC_DOWNLOAD=0 HITEX_AURIX_MEMTOOL_ROOT="C:\Program Files (x86)\Infineon\Memtool 4.7" ISPROTECTINGMODEL=NOTPROTECTING
